USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE WAREHOUSE HC_AISQL_WH;
CREATE OR REPLACE DATABASE HC_AISQL_DB;
CREATE OR REPLACE SCHEMA HC_AISQL_DB.HC_AISQL_SCHEMA;

USE WAREHOUSE HC_AISQL_WH;
USE DATABASE HC_AISQL_DB;
USE SCHEMA HC_AISQL_SCHEMA;

CREATE OR REPLACE STAGE HC_AISQL_STAGE 
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

-- Load files into the stage via Snowsight UI

-- List files in the stage
SELECT * FROM DIRECTORY(@HC_AISQL_DB.HC_AISQL_SCHEMA.HC_AISQL_STAGE);

-- Load medical images(jpeg files) directly from stage using FILE data type
CREATE OR REPLACE TABLE HC_AISQL_DB.HC_AISQL_SCHEMA.MEDICAL_IMAGES AS
SELECT TO_FILE(FILE_URL) IMAGE_FILE, *
FROM DIRECTORY(@HC_AISQL_DB.HC_AISQL_SCHEMA.HC_AISQL_STAGE)
WHERE RELATIVE_PATH LIKE 'MEDICAL_IMAGES/%';

SELECT * FROM HC_AISQL_DB.HC_AISQL_SCHEMA.MEDICAL_IMAGES;

SELECT FL_GET_RELATIVE_PATH(IMAGE_FILE) 
FROM HC_AISQL_DB.HC_AISQL_SCHEMA.MEDICAL_IMAGES;

USE DATABASE HC_AISQL_DB;
USE SCHEMA HC_AISQL_SCHEMA;

-- Use Cortex AI_COMPLETE SQL function for medical images classification
-- with CLAUDE-3-5-SONNET LLM
SELECT 
IMAGE_FILE,
AI_COMPLETE('claude-3-5-sonnet',
PROMPT('Classify the input image {0} in no more than 2 words', IMAGE_FILE)) AS AI_COMPLETE_IMAGE_CLASSIFICATION
FROM MEDICAL_IMAGES;

-- Filter with Cortex AI_FILTER SQL function
SELECT 
IMAGE_FILE
FROM MEDICAL_IMAGES
WHERE AI_FILTER(PROMPT('This medical image {0} is a Chest X-ray', IMAGE_FILE)) ;

-- Use AI_CLASSIFY to categorize images into custom categories
SELECT 
IMAGE_FILE,
AI_CLASSIFY(PROMPT('Please classify this medical image {0}', IMAGE_FILE),
        ['X-ray', 'CT', 'MRI', 'Ultrasound','PET','Other']):labels[0]::STRING as AI_CLASSIFY_CLASSIFICATION
from MEDICAL_IMAGES;

-- Store AI classifications
ALTER TABLE MEDICAL_IMAGES ADD COLUMN AI_COMPLETE_IMAGE_CLASSIFICATION STRING;

UPDATE MEDICAL_IMAGES 
SET AI_COMPLETE_IMAGE_CLASSIFICATION = AI_COMPLETE('claude-3-5-sonnet',
PROMPT('Classify the input image {0} in no more than 2 words', IMAGE_FILE));

ALTER TABLE MEDICAL_IMAGES ADD COLUMN AI_CLASSIFY_CLASSIFICATION STRING;

UPDATE MEDICAL_IMAGES 
SET AI_CLASSIFY_CLASSIFICATION = AI_CLASSIFY(PROMPT('Please classify this medical image {0}', IMAGE_FILE),
        ['X-ray', 'CT', 'MRI', 'Ultrasound','PET','Other']):labels[0]::STRING;

DESCRIBE TABLE MEDICAL_IMAGES;

SELECT * FROM MEDICAL_IMAGES;






