USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE HL7_FHIR 
    COMMENT = 'HL7 FHIR DATABASE';
    
CREATE OR REPLACE SCHEMA HL7_FHIR.HL7_FHIR_R4;

CREATE OR REPLACE WAREHOUSE HL7_FHIR_WH
    WAREHOUSE_SIZE = 'XSMALL'
    INITIALLY_SUSPENDED = FALSE
    AUTO_SUSPEND = 600
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT=1
    MAX_CLUSTER_COUNT=1
    SCALING_POLICY='STANDARD'
    COMMENT = '';

CREATE OR REPLACE NOTEBOOK FHIR_NB
    QUERY_WAREHOUSE=HL7_FHIR_WH
    MAIN_FILE = 'FHIR_NB.ipynb'
    WAREHOUSE=HL7_FHIR_WH;